<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>BillMaxAPP</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Enable XAML source generation for faster build times and improved performance.
		     This generates C# code from XAML at compile time instead of runtime inflation.
		     To disable, remove this line.
		     For individual files, you can override by setting Inflator metadata:
		       <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
		       <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<!-- Display name -->
		<ApplicationTitle>BillMaxAPP</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.billmaxapp</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)' == 'Release|net10.0-android'">
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidPackageFormats>apk</AndroidPackageFormats>

    <AndroidSigningKeyStore>BillMax-release.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>billmax</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>Sunil@1998</AndroidSigningKeyPass>
    <AndroidSigningStorePass>Sunil@1998</AndroidSigningStorePass>
</PropertyGroup>


	<!-- ========================================================= -->
	<!-- ANDROID APK CONFIGURATION -->
	<!-- ========================================================= -->




	<!-- ========================================================= -->
	<!-- APP ICON / SPLASH / IMAGES -->
	<!-- ========================================================= -->

	<ItemGroup>

		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Images\billmax_logo.png" Color="#FFFFFF" BaseSize="300,300" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

	</ItemGroup>


	<!-- ========================================================= -->
	<!-- NUGET PACKAGES -->
	<!-- ========================================================= -->

	<ItemGroup>

		<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.5" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />

		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />

		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />

	</ItemGroup>


	<!-- ========================================================= -->
	<!-- XAML FILES -->
	<!-- ========================================================= -->

	<ItemGroup>

		<MauiXaml Update="AppShellStore.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Account\ChangePasswordPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\AdminDashboardPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Billing\CreateBillPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Billing\InvoiceDetailsPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Billing\InvoiceListPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\CartBar.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\CartBottomSheet.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\CategorySidebar.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\DashboardCard.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\LowStocks.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\ProductCard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\RecentBillsCard.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\SalesTrendCard.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\StoreBottomBar.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Components\TopStoreCard.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\GSTSettingPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\POs\PosPrinterPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Products\CategoryFormPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Products\CategoryListPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Products\ProductFormPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Products\ProductListPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\ProfilePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\ReportPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Reports\DailyReportPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Reports\MonthlyReportPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\SplashPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\StoreDashboardPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\StoreMgntPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Store\InvoiceSettingPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

		<MauiXaml Update="Views\Store\StoreProfilePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>

	</ItemGroup>

</Project>